apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  version: 2.6.0
  replicas: 1
  consumer:
    bootstrapServers: {streams_endpoint_url}:9094
    groupId: my-source-group-id
    config:
      auto.offset.reset: earliest
    tls:
      trustedCertificates:
        - secretName: kafka-cluster-cluster-ca-cert
          certificate: ca.crt
    authentication:
      type: oauth
      clientId: clientid
      clientSecret:
        key: secret
        secretName: clientsecret
      disableTlsHostnameVerification: false
      tokenEndpointUri: https://{auth_endpoint_url}/auth/realms/pro-realm/protocol/openid-connect/token
  producer:
    bootstrapServers: kafka-cluster-kafka-bootstrap.localkafka:9092
  #    authentication:
  #      type: plain
  #      username: ""
  #      passwordSecret:
  #        secretName: my-user-secret
  #        password: password

  whitelist: *
  readinessProbe: 
    initialDelaySeconds: 15
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
